modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/CookieCNetwork/Chipped/issues"

[[mods]]
modId="chipped"
version="${file.jarVersion}"
logoFile="Chipped_Logo.png"
displayName="Chipped"
credits="Code: Grim, Inforno, CodexAdrian, ThatGravyBoat, MsRandom (Ashh). Textures/Art: Kekie6, Marc-IceBlade, SunsetSoup, BrotherEarth967, Joosh, Valila, ArtistMonster, Zilver"
authors="grimbo"
description='''
'''