modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/CookieCNetwork/Chipped/issues"
[[mods]]
modId="chipped"
version="1.0.0"
displayName="Chipped"
credits="Grimbo for the code, Kekie6 for textures"
authors="Grimbo"
description='''
'''