modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="All rights reserved"
[[mods]] #mandatory
modId="chipped" #mandatory
#version="1.0.0" #mandatory
displayName="Chipped" #mandatory
credits="Grimbo for the code, Kekie6 for textures" #optional
authors="Grimbo" #optional
description='''
This is a long form description of the mod. You can write whatever you want here
'''
